# fly.toml app configuration file generated for empty-glitter-2031 on 2023-07-29T21:14:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-glitter-2031"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
